awk 'FNR==1{print ""}{print}' ../*M*dicopt2.conopt* > M.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*M*dicopt2.ipopth* > M.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*M*dicopt2.knitro* > M.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*M*dicopt2.mosek* > M.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*M*sbb.conopt* > M.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*M*sbb.ipopth* > M.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*M*sbb.knitro* > M.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*M*sbb.mosek* > M.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*M*sbb.cplex* > M.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*M*baron* > M.baron.trc
awk 'FNR==1{print ""}{print}' ../*M*antigone* > M.antigone.trc
awk 'FNR==1{print ""}{print}' ../*M*knitro.knitro* > M.knitro.trc
awk 'FNR==1{print ""}{print}' ../*M*scip.scip* > M.scip.trc
awk 'FNR==1{print ""}{print}' ../*M*cplex.cplex* > M.cplex.trc
awk 'FNR==1{print ""}{print}' ../*M*mosek.mosek* > M.mosek.trc

awk 'FNR==1{print ""}{print}' ../*HRL*dicopt2.conopt* > HRL.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRL*dicopt2.ipopth* > HRL.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRL*dicopt2.knitro* > HRL.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRL*dicopt2.mosek* > HRL.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRL*sbb.conopt* > HRL.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRL*sbb.ipopth* > HRL.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRL*sbb.knitro* > HRL.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRL*sbb.mosek* > HRL.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRL*sbb.cplex* > HRL.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRL*baron* > HRL.baron.trc
awk 'FNR==1{print ""}{print}' ../*HRL*antigone* > HRL.antigone.trc
awk 'FNR==1{print ""}{print}' ../*HRL*knitro.knitro* > HRL.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRL*scip.scip* > HRL.scip.trc
awk 'FNR==1{print ""}{print}' ../*HRL*cplex.cplex* > HRL.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRL*mosek.mosek* > HRL.mosek.trc

awk 'FNR==1{print ""}{print}' ../*HRconv*dicopt2.conopt* > HRconv.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*dicopt2.ipopth* > HRconv.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*dicopt2.knitro* > HRconv.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*dicopt2.mosek* > HRconv.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*sbb.conopt* > HRconv.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*sbb.ipopth* > HRconv.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*sbb.knitro* > HRconv.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*sbb.mosek* > HRconv.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*sbb.cplex* > HRconv.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*baron* > HRconv.baron.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*antigone* > HRconv.antigone.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*knitro.knitro* > HRconv.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*scip.scip* > HRconv.scip.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*cplex.cplex* > HRconv.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRconv*mosek.mosek* > HRconv.mosek.trc

awk 'FNR==1{print ""}{print}' ../*HRc.*dicopt2.conopt* > HRc.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*dicopt2.ipopth* > HRc.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*dicopt2.knitro* > HRc.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*dicopt2.mosek* > HRc.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*sbb.conopt* > HRc.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*sbb.ipopth* > HRc.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*sbb.knitro* > HRc.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*sbb.mosek* > HRc.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*sbb.cplex* > HRc.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*baron* > HRc.baron.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*antigone* > HRc.antigone.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*knitro.knitro* > HRc.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*scip.scip* > HRc.scip.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*cplex.cplex* > HRc.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRc.*mosek.mosek* > HRc.mosek.trc

awk 'FNR==1{print ""}{print}' ../*HR.*dicopt2.conopt* > HR.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HR.*dicopt2.ipopth* > HR.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HR.*dicopt2.knitro* > HR.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HR.*dicopt2.mosek* > HR.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HR.*sbb.conopt* > HR.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HR.*sbb.ipopth* > HR.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HR.*sbb.knitro* > HR.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HR.*sbb.mosek* > HR.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HR.*sbb.cplex* > HR.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HR.*baron* > HR.baron.trc
awk 'FNR==1{print ""}{print}' ../*HR.*antigone* > HR.antigone.trc
awk 'FNR==1{print ""}{print}' ../*HR.*knitro.knitro* > HR.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HR.*scip.scip* > HR.scip.trc
awk 'FNR==1{print ""}{print}' ../*HR.*cplex.cplex* > HR.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HR.*mosek.mosek* > HR.mosek.trc

awk 'FNR==1{print ""}{print}' ../*HR2*dicopt2.conopt* > HR2.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HR2*dicopt2.ipopth* > HR2.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HR2*dicopt2.knitro* > HR2.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HR2*dicopt2.mosek* > HR2.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HR2*sbb.conopt* > HR2.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HR2*sbb.ipopth* > HR2.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HR2*sbb.knitro* > HR2.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HR2*sbb.mosek* > HR2.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HR2*sbb.cplex* > HR2.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HR2*baron* > HR2.baron.trc
awk 'FNR==1{print ""}{print}' ../*HR2*antigone* > HR2.antigone.trc
awk 'FNR==1{print ""}{print}' ../*HR2*knitro.knitro* > HR2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HR2*scip.scip* > HR2.scip.trc
awk 'FNR==1{print ""}{print}' ../*HR2*cplex.cplex* > HR2.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HR2*mosek.mosek* > HR2.mosek.trc
