# Create file with all the lines corresponding to a solverproblem combination
awk 'FNR==1{print ""}{print}' ../*BM*dicopt2.conopt* > BM.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*BM*dicopt2.ipopth* > BM.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*BM*dicopt2.knitro* > BM.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*BM*dicopt2.mosek* > BM.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*BM*sbb.conopt* > BM.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*BM*sbb.ipopth* > BM.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*BM*sbb.knitro* > BM.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*BM*sbb.mosek* > BM.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*BM*sbb.cplex* > BM.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*BM*baron* > BM.baron.trc
awk 'FNR==1{print ""}{print}' ../*BM*antigone* > BM.antigone.trc
awk 'FNR==1{print ""}{print}' ../*BM*knitro.knitro* > BM.knitro.trc
awk 'FNR==1{print ""}{print}' ../*BM*scip.scip* > BM.scip.trc
awk 'FNR==1{print ""}{print}' ../*BM*cplex.cplex* > BM.cplex.trc
awk 'FNR==1{print ""}{print}' ../*BM*mosek.mosek* > BM.mosek.trc

awk 'FNR==1{print ""}{print}' ../*HRL*dicopt2.conopt* > HRL.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRL*dicopt2.ipopth* > HRL.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRL*dicopt2.knitro* > HRL.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRL*dicopt2.mosek* > HRL.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRL*sbb.conopt* > HRL.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRL*sbb.ipopth* > HRL.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRL*sbb.knitro* > HRL.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRL*sbb.mosek* > HRL.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRL*sbb.cplex* > HRL.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRL*baron* > HRL.baron.trc
awk 'FNR==1{print ""}{print}' ../*HRL*antigone* > HRL.antigone.trc
awk 'FNR==1{print ""}{print}' ../*HRL*knitro.knitro* > HRL.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRL*scip.scip* > HRL.scip.trc
awk 'FNR==1{print ""}{print}' ../*HRL*cplex.cplex* > HRL.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRL*mosek.mosek* > HRL.mosek.trc

awk 'FNR==1{print ""}{print}' ../*HRc*dicopt2.conopt* > HRc.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRc*dicopt2.ipopth* > HRc.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRc*dicopt2.knitro* > HRc.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRc*dicopt2.mosek* > HRc.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRc*sbb.conopt* > HRc.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRc*sbb.ipopth* > HRc.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRc*sbb.knitro* > HRc.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRc*sbb.mosek* > HRc.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRc*sbb.cplex* > HRc.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRc*baron* > HRc.baron.trc
awk 'FNR==1{print ""}{print}' ../*HRc*antigone* > HRc.antigone.trc
awk 'FNR==1{print ""}{print}' ../*HRc*knitro.knitro* > HRc.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRc*scip.scip* > HRc.scip.trc
awk 'FNR==1{print ""}{print}' ../*HRc*cplex.cplex* > HRc.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRc*mosek.mosek* > HRc.mosek.trc

awk 'FNR==1{print ""}{print}' ../*HR2*dicopt2.conopt* > HR2.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HR2*dicopt2.ipopth* > HR2.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HR2*dicopt2.knitro* > HR2.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HR2*dicopt2.mosek* > HR2.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HR2*sbb.conopt* > HR2.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HR2*sbb.ipopth* > HR2.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HR2*sbb.knitro* > HR2.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HR2*sbb.mosek* > HR2.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HR2*sbb.cplex* > HR2.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HR2*baron* > HR2.baron.trc
awk 'FNR==1{print ""}{print}' ../*HR2*antigone* > HR2.antigone.trc
awk 'FNR==1{print ""}{print}' ../*HR2*knitro.knitro* > HR2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HR2*scip.scip* > HR2.scip.trc
awk 'FNR==1{print ""}{print}' ../*HR2*cplex.cplex* > HR2.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HR2*mosek.mosek* > HR2.mosek.trc

awk 'FNR==1{print ""}{print}' ../*HRS*dicopt2.conopt* > HRS.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRS*dicopt2.ipopth* > HRS.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRS*dicopt2.knitro* > HRS.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRS*dicopt2.mosek* > HRS.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRS*sbb.conopt* > HRS.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRS*sbb.ipopth* > HRS.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRS*sbb.knitro* > HRS.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRS*sbb.mosek* > HRS.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRS*sbb.cplex* > HRS.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRS*baron* > HRS.baron.trc
awk 'FNR==1{print ""}{print}' ../*HRS*antigone* > HRS.antigone.trc
awk 'FNR==1{print ""}{print}' ../*HRS*knitro.knitro* > HRS.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRS*scip.scip* > HRS.scip.trc
awk 'FNR==1{print ""}{print}' ../*HRS*cplex.cplex* > HRS.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRS*mosek.mosek* > HRS.mosek.trc

awk 'FNR==1{print ""}{print}' ../*HRC*dicopt2.conopt* > HRC.dicopt2.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRC*dicopt2.ipopth* > HRC.dicopt2.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRC*dicopt2.knitro* > HRC.dicopt2.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRC*dicopt2.mosek* > HRC.dicopt2.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRC*sbb.conopt* > HRC.sbb.conopt.trc
awk 'FNR==1{print ""}{print}' ../*HRC*sbb.ipopth* > HRC.sbb.ipopth.trc
awk 'FNR==1{print ""}{print}' ../*HRC*sbb.knitro* > HRC.sbb.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRC*sbb.mosek* > HRC.sbb.mosek.trc
awk 'FNR==1{print ""}{print}' ../*HRC*sbb.cplex* > HRC.sbb.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRC*baron* > HRC.baron.trc
awk 'FNR==1{print ""}{print}' ../*HRC*antigone* > HRC.antigone.trc
awk 'FNR==1{print ""}{print}' ../*HRC*knitro.knitro* > HRC.knitro.trc
awk 'FNR==1{print ""}{print}' ../*HRC*scip.scip* > HRC.scip.trc
awk 'FNR==1{print ""}{print}' ../*HRC*cplex.cplex* > HRC.cplex.trc
awk 'FNR==1{print ""}{print}' ../*HRC*mosek.mosek* > HRC.mosek.trc
